#!/usr/bin/env bash

# +------------------------------------------------------------------------------------------+
# + FILE: dBackup                                                                            +
# +                                                                                          +
# + DESCRIPTION: dBackup (Data Backup) is a parameterized wrapper written in bash around     +
# +              different backup utilities for Linux/UNIX-like systems.                     +
# +                                                                                          +
# + AUTHOR: Saad Ali (https://github.com/NIXKnight)                                          +
# +                                                                                          +
# + LICENSE: MIT License (See LICENSE file)                                                  +
# +------------------------------------------------------------------------------------------+

# PARAMETERS TO BE USED BY THE SCRIPT

SHORT_OPTS="hd:,D:,c:"
LONG_OPTS="help,directory:,backup-directory:,strftime:,compression-format:"
OPTS=$(getopt --shell bash --options $SHORT_OPTS --longoptions $LONG_OPTS -- $@)
eval set -- "$OPTS"

# PARAMETER PARSING START

while true ; do
  case "$1" in
    -h|--help)
      exit 0
      ;;
    -d|--directory) # This parameter is used to set the target directory or directories that
                    # will be included in a backup.
      shift 2
      ;;
    -D|--backup-directory) # This parameter is used to set the master/destination backup
                           # directory.
      shift 2
      ;;
    -c|--compression-format) # This parameter is used to set a compression format to either
                             # gzip or bzip2.
      shift 2
      ;;
    --strftime) # This parameter is used to set a custom date/time format which will be used to
                # set backup directory name.
      shift 2
      ;;
    --)
      shift
      break
      ;;
    *)
      exit 1
      ;;
  esac
done

# PARAMETER PARSING END
